"""Assemble a Blogger page for a subject from its published units.

Output matches what the app already parses: a hidden div whose id starts with
gctc-app-videos, containing the nodes/videos JSON. Every video carries an explicit
`id`, because the app's fallback id is slug(title)+hash(url), which collides
whenever titles and URLs repeat.

Chapters whose timestamps are only one or two seconds apart are dropped. Those are
the alignment fallback: a chapter whose anchor phrase was never spoken gets an
even-split time and is then forced strictly increasing, which bunches them at the
end of the video. A marker pointing at the wrong place is worse than no marker.
"""

from __future__ import annotations

import argparse
import datetime
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from common import ROOT, load_syllabus, log, read_manifest  # noqa: E402

PAGES = ROOT / "pages"
MIN_CHAPTER_GAP = 3


def clean_chapters(chapters: list[dict]) -> tuple[list[dict], int]:
    kept: list[dict] = []
    for c in chapters or []:
        if kept and c["t"] - kept[-1]["t"] <= MIN_CHAPTER_GAP:
            continue
        kept.append({"t": c["t"], "label": c["label"]})
    return kept, len(chapters or []) - len(kept)


def subject_node(syl: dict) -> dict:
    """The subject as an inline node, ready to paste into a parent page."""
    subj = syl["subject"]
    man = read_manifest()["units"]
    videos = []
    for u in syl["units"]:
        rec = man.get(f"{subj['id']}/{u['id']}", {})
        entry = rec.get("catalog_entry") or {}
        url = entry.get("url")
        if not url or url.startswith("TBD"):
            log(f"  unit {u['id']}: not published yet, omitted")
            continue
        chapters, dropped = clean_chapters(rec.get("chapters"))
        if dropped:
            log(f"  unit {u['id']}: dropped {dropped} fallback chapter(s)")
        dur = rec.get("duration_sec") or 0
        video = {
            "id": f"{subj['id']}-{u['id']}",
            "title": f"Unit {u['n']}: {u['title']}",
            "url": url,
            "subtitle": f"{dur // 60} min" if dur else None,
            "dur": dur or None,
            "thumb": entry.get("thumb"),
            "vtt": entry.get("vtt"),
            "chapters": chapters or None,
        }
        videos.append({k: v for k, v in video.items() if v})
    return {"id": subj["id"], "title": subj["title"], "videos": videos}


def page_html(syl: dict, node: dict) -> str:
    subj = syl["subject"]
    page_id = f"app-videos-{subj['id']}"
    cfg = {
        "title": subj["title"],
        "updatedAt": datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "videos": node["videos"],
    }
    body = json.dumps(cfg, indent=2, ensure_ascii=False)
    return f"""<!--
  ============================================================================
  GCTC PORTAL  -  {subj['title'].upper()}  (page: /p/{page_id}.html)
  ============================================================================
  {subj['code']}  |  {subj['branch']}  |  Year {subj['year']}  Semester {subj['semester']}

  Generated by video-worker. Durations and chapter times were measured from the
  finished files; nothing here is estimated. Paste Drive links exactly as they
  are - the app normalises them to a streaming URL itself.
  ============================================================================
-->
<div id="gctc-{page_id}-config" style="display:none">
{body}
</div>
"""


def main() -> None:
    ap = argparse.ArgumentParser(description="Build the Blogger page for a subject.")
    ap.add_argument("--syllabus", required=True)
    ap.add_argument("--node-only", action="store_true",
                    help="emit just the subject node, to paste into a parent page")
    a = ap.parse_args()

    syl = load_syllabus(a.syllabus)
    node = subject_node(syl)
    if not node["videos"]:
        raise SystemExit("no published units yet; run publish.py first")

    PAGES.mkdir(parents=True, exist_ok=True)
    sid = syl["subject"]["id"]

    page = PAGES / f"app-videos-{sid}.html"
    page.write_text(page_html(syl, node), encoding="utf-8")

    # Indented to sit inside an existing nodes array in a parent page.
    node_txt = "\n".join("        " + ln
                         for ln in json.dumps(node, indent=2,
                                              ensure_ascii=False).splitlines())
    node_file = PAGES / f"node-{sid}.txt"
    node_file.write_text(node_txt + "\n", encoding="utf-8")

    log(f"{len(node['videos'])} unit(s) written")
    log(f"  page: {page}")
    log(f"  node: {node_file}")
    if a.node_only:
        print(node_txt)


if __name__ == "__main__":
    main()
